### ISSUE TITLE
Could you please make the source data which are in graphson format public?

### ISSUE THREAD

**Issue by wangtua1** [stucco/auto-labeled-corpus#2]
I have been concentrating on this project for nearly two months, I hope I can review the training and tagging process on my computer, but I noticed that the public files do not include the data in graphson format  .Could you please make them public?

**Comment by mikeiannacone** [comment]
Sorry for the delay.  Which files specifically did you need?

**Comment by csyzhang** [comment]
@mikeiannacone I am quite interested in this work and I want to try it on my setup. I had an error message saying the graphson files are missing. Do you know where I can get the .graphson files? For example, "nvdcve-2.0-2010.graphson". Thanks.

**Comment by mikeiannacone** [comment]
Moved to #5 - hopefully this covers everything that's needed, if not we can continue w/ that issue instead of this one.
